---
- name: Ensure go lang is installed and configured correctly
  hosts: factory

  tasks:
    - name: Set fact for $HOME
      ansible.builtin.set_fact:
        HOME: "{{ lookup('env', 'HOME') }}"

    - name: When MacOSX ensure Go is installed
      community.general.homebrew:
        name:
          - go
          - golangci-lint
        state: latest
      retries: "{{ default_retries }}"
      delay: "{{ default_delay }}"
      register: result
      until: result is succeeded
      when: ( ansible_distribution == 'MacOSX' )

    - name: When Archlinux ensure Go is installed
      community.general.pacman:
        name: "go"
        state: latest
      retries: "{{ default_retries }}"
      delay: "{{ default_delay }}"
      register: result
      until: result is succeeded
      become: yes
      when: ( ansible_distribution == 'Archlinux' )

    - name: Ensure {{ HOME }}/go folders exists
      ansible.builtin.file:
        path: "{{ HOME }}/go/{{ item }}"
        state: directory
        mode: 0775
      with_items:
        - bin
        - pkg
        - src

    - name: Ensure golint is installed
      command: /bin/bash -c 'export GOBIN="$HOME/go/bin"; export GOPATH="$HOME/go"; export PATH="$GOBIN:$PATH"; go get -u golang.org/x/lint/golint'
      retries: "{{ default_retries }}"
      delay: "{{ default_delay }}"
      register: result
      until: result is succeeded

    - name: When Archlinux ensure golangci-lint is installed
      ansible.builtin.shell: export GOBIN="$HOME/go/bin"; export GOPATH="$HOME/go"; export PATH="$GOBIN:$PATH"; curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
      when: ( ansible_distribution == 'Archlinux' )
