---
  # Install Chef InSpec via gem (https://github.com/inspec/inspec) vice a package relevant to operating 
  # system (https://docs.chef.io/inspec/install/)
  #
  - ansible.builtin.debug:
      msg: Installing InSpec requiring lots and lots of Ruby gems. This will take sometime... Go have some pie.

  - name: Ensure inspec-bin gem is installed
    ansible.builtin.shell: bash -c "source ~/.bash_profile && gem install inspec-bin"

  - name: 'RubyZip has released v2.3.1 "dummy" release that repeatedly splashes a warning about v3.0 coming.  Grr!  Get rid of it.'
    ansible.builtin.shell: bash -c "source ~/.bash_profile && gem uninstall --force rubyzip && gem install rubyzip -v 2.3.0"

# https://docs.chef.io/chef_license_accept/
