---
- name: Install factory dependencies 
  hosts: factory
  remote_user: root
  vars:
    default_delay: 10
    default_retries: 60
    ruby_version: 3.0.1
    supported_host_os:
      - MacOSX
      - Archlinux
    
  tasks:
  - name: Echo ansible distribution
    ansible.builtin.debug:
      msg: '{{ inventory_hostname }} host is running {{ ansible_distribution }}:{{ ansible_distribution_release }} with an IP address if {{ ansible_default_ipv4.address }}'

  - name: Fail if OS is not MacOSX or ArchLinux
    fail:
      msg: '{{ ansible_distribution }} - {{ ansible_distribution_release }} is not MacOSX or ArchLinux'
    when:  ansible_distribution not in supported_host_os

  - name: Include common.yml
    include: common.yaml

  - name: Ensure pyenv is installed and configured
    include: pyenv.yaml

  - name: Ensure Go is installed and configured
    include: go.yaml

  - name: Ensure sonar-scanner cli is installed and configured
    include: sonar-scanner-cli.yaml

  - name: Ensure rvm and ruby {{ ruby_version }} is installed
    include: ruby.yaml

  - name: Ensure InSpec is installed
    include: inspec.yaml

  - name: Ensure neovim is installed and configured 
    include: neovim.yaml
