---
- name: Ensure sonar-scanner is installed
  hosts: factory

  tasks:
    - name: Ensure sonar-scanner is installed
      community.general.homebrew:
        name: "sonar-scanner"
        state: latest
      retries: "{{ default_retries }}"
      delay: "{{ default_delay }}"
      register: result
      until: result is succeeded
      when: ( ansible_distribution == 'MacOSX' )

    - name: Install packages from AUR using a yay AUR helper
      community.general.pacman:
        name: sonar-scanner
        state: latest
        executable: yay
      when: ( ansible_distribution == 'Archlinux' )
